package br.com.auttar.common.constants;

public class AppConstants {
	public static final int RESPONSE_CODE_SUCCESS=0;
	public static final int RESPONSE_CODE_GENERIC_ERROR=1;
	public static final int RESPONSE_CODE_NOT_FOUND=2;
	public static final int RESPONSE_CODE_ERROR_QRCODE = 3;
	public static final int RESPONSE_CODE_CONFIGURATION_ERROR = 4;
	public static final int RESPONSE_CODE_AUTOMATION_OFFLINE_WARNING = 5;
	public static final int DATABASE_ERROR = 6;

	public static final String RESPONSE_MESSAGE_OPERACAO_NAO_DISPONIVEL = "OPERACAO NAO DISPONIVEL";
	public static final String RESPONSE_MESSAGE_ERROR_AUTOMATION_COMUNIC = "ERRO DE COMUNICACAO COM A AUTOMACAO";
	public static final String RESPONSE_MESSAGE_REGISTRO_NAO_ENCONTRADO = "REGISTRO NAO ENCONTRADO";
	public static final String RESPONSE_MESSAGE_ERROR_QRCODE = "ERRO AO GERAR O QRCODE";
	public static final String RESPONSE_MESSAGE_ERROR_BROKER = "ERRO DE COMUNICACAO COM O BARRAMENTO DE SERVICOS";
	public static final String RESPONSE_MESSAGE_ERROR_GENERIC = "ERRO INESPERADO";
	public static final String RESPONSE_MESSAGE_ERROR_COMPANY_CODE = "CODIGO DA EMPRESA NAO INFORMADO";
	public static final String RESPONSE_MESSAGE_MISSING_ID = "IDENTIFICADOR NAO INFORMADO";
	public static final String RESPONSE_MESSAGE_ERROR_AMOUNT = "AMOUNT NAO INFORMADO";
	public static final String RESPONSE_MESSAGE_ERROR_STORE_CODE = "CODIGO DA LOJA NAO INFORMADO";
	public static final String RESPONSE_MESSAGE_ERROR_PAYMENT_POS_CODE = "CODIGO DE PAGAMENTO DO POS NAO INFORMADO";
	public static final String RESPONSE_MESSAGE_DATABASE_ERROR = "ERRO AO ACESSAR O BANCO DE DADOS.";
	public static final String RESPONSE_MESSAGE_NOT_FOOUND = "REGISTRO NAO ENCONTRADO";
	public static final String RESPONSE_MESSAGE_NUMERO_REGISTRO_NAO_INFORMADO = "NUMERO REGISTRO NAO INFORMADO";
	public static final String RESPONSE_MESSAGE_GRUPO_MULTI_EC_NAO_INFORMADO = "GRUPO MULTI EC NAO INFORMADO";
	public static final String RESPONSE_MESSAGE_CODIGO_EMPRESA_NAO_INFORMADO = "CODIGO EMPRESA NAO INFORMADO";
	public static final String RESPONSE_MESSAGE_NUMERO_LOJA_NAO_INFORMADO = "NUMERO LOJA NAO INFORMADO";
	public static final String RESPONSE_MESSAGE_NUMERO_PDV_NAO_INFORMADO = "NUMERO PDV NAO INFORMADO";
}
